import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Container } from "@chakra-ui/react";
import { gql } from "@apollo/client";

import DemoModule from "../modules/demo";
import client from "../utils/apollo-client";
interface Props {
  daiData: any;
}

const Demo: NextPage<Props> = ({ daiData }) => {
  console.log("daiData", daiData);
  return (
    <Container>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DemoModule />
    </Container>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // https://www.apollographql.com/blog/apollo-client/next-js/next-js-getting-started/
  // https://docs.uniswap.org/protocol/V2/guides/interface-integration/using-the-api
  const { data } = await client.query({
    query: gql`
      query tokens($tokenAddress: Bytes!) {
        tokens(where: { id: $tokenAddress }) {
          derivedETH
          totalLiquidity
        }
      }
    `,
    variables: {
      tokenAddress: "0x6b175474e89094c44da98b954eedeac495271d0f",
    },
  });

  console.log("data", data);
  return {
    props: {
      daiData: data.tokens,
    },
  };
};

export default Demo;
