import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "@chakra-ui/react";
import DemoModule from "../modules/demo";

const Demo: NextPage = () => (
  <Container>
    <Head>
      <title>Demo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <DemoModule />
  </Container>
);

export default Demo;
