import type { NextPage } from "next";
import Head from "next/head";
import { Container } from "@chakra-ui/react";

import { Form, Misc } from "../modules/design";

const Design: NextPage = () => (
  <Container>
    <Head>
      <title>Hello</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Form />
    <Misc />
  </Container>
);

export default Design;
