import { Center, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { ColorSchemeToggle } from "../modules/common";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack>
        <Center py={2}>
          <ColorSchemeToggle />
        </Center>
        <Center>
          <Link href="/demo/custom-contract">
            <a className="cursor-pointer">Custom Contract</a>
          </Link>
        </Center>
        <Center>
          <Link href="/demo/uniswapv2">
            <a className="cursor-pointer">Uniswapv2 Contract</a>
          </Link>
        </Center>
        <Center>
          <Link href="/demo/uniswapv2-gql">
            <a className="cursor-pointer">Uniswapv2 Subgraph</a>
          </Link>
        </Center>
      </VStack>
    </div>
  );
};

export default Home;
