// import styles from "../styles/Home.module.css";
import { Center } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { ColorSchemeToggle } from "../modules/common";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center py={2}>
        <ColorSchemeToggle />
      </Center>
      <Center>
        <Link href="/demo">
          <a className="cursor-pointer">Go to Demo</a>
        </Link>
      </Center>
    </div>
  );
};

export default Home;
