// import styles from "../styles/Home.module.css";
import type { NextPage } from "next";
import Head from "next/head";

import { CryptoForm } from "../modules/home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CryptoForm />
    </div>
  );
};

export default Home;
